Dear $name$,

We are notifying you that we have deprecated your app, $app_name$, in the Discovery Environment (DE).
This usually happens when a newer version of this app is made publicly available in the DE.
While the older app is still viewable by its direct link (below), the deprecated version can no longer be used or searched for in the Discovery Environment.
 
$app_link$

If you believe this app should not have been deprecated, please contact support@cyverse.org.

Thank you,
Team CyVerse
