Dear $name$,

Your app, $app_name$, has been deprecated in the Discovery Environment (DE).
This usually happens when a newer version of the app is made publicly available in the DE.
The deprecated app is still viewable by its direct link (below), but it can no longer be found (via Search) or launched in the Discovery Environment.
 
$app_link$

If this app should not have been deprecated, please contact support@cyverse.org.

Thank you,
Team CyVerse
